import BottomHeader from '@/components/bottom-header/page';
import TopHeader from '@/components/top-header/page';
import { BottomNavProvider } from '@/components/bottom-nav/provider';
import ContentRouter from '@/components/bottom-nav/ContentRouter';
import type { Metadata } from 'next';
import { Geist, Geist_Mono, Inter } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';
import MarketTicker from '@/components/market-ticker';

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang='en'
      className={cn(
        'h-full',
        'antialiased',
        geistSans.variable,
        geistMono.variable,
        'font-sans',
        inter.variable,
      )}
    >
      <body className='min-h-full flex flex-col bg-background pt-12 pb-16'>
        <BottomNavProvider>
          <TopHeader />
          <MarketTicker />
          <ContentRouter>{children}</ContentRouter>
          <BottomHeader />
        </BottomNavProvider>
      </body>
    </html>
  );
}
